### ISSUE TITLE
Blog - Threat Modeling and Ortelius Machine Learning

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/outreach#37]
A blog on the efforts of using the Ortelius consolidated security and devops data for building ML workflows to address threat modeling.

**Comment by raj-rox** [comment]
This is a cool topic!
Have started working on it here -- https://docs.google.com/document/d/1DJHVOALkv-ew_g5Hp2VfL5ec5Hi2LYD_CJLPjaXPHUs/edit?usp=sharing

**Comment by raj-rox** [comment]
@TracyRagan Have worked on the blog here - Can you please review it? 

https://docs.google.com/document/d/1DJHVOALkv-ew_g5Hp2VfL5ec5Hi2LYD_CJLPjaXPHUs/edit?usp=sharing

(Have used markdown within Google Docs, still getting used to VSCode)

**Comment by raj-rox** [comment]
Edited and published by @TracyRagan 
https://ortelius.io/blog/2024/04/09/how-ortelius-models-threats-with-ml-workflows-a-roadmap/
