### ISSUE TITLE
Blog - What is Threat Modeling

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/outreach#38]
A blog that explains what threat modeling is and where the data is coming from. A discussion around Mitre Attack  should be included and introduced. 
https://www.mitre.org/focus-areas/cybersecurity/mitre-attack

**Comment by Elizabeth-CR** [comment]
![Risks](https://github.com/ortelius/outreach/assets/90054419/828cfbc4-f525-4ab1-a03c-968e1bd8686c)
[ThreatModeling.md](https://github.com/ortelius/outreach/files/14769097/ThreatModeling.md)

**Comment by Elizabeth-CR** [comment]
![Risks](https://github.com/ortelius/outreach/assets/90054419/20fcc329-7608-42ef-b50a-ac8399de750e)
[ThreatModeling.md](https://github.com/ortelius/outreach/files/14769113/ThreatModeling.md)

**Comment by TracyRagan** [comment]
Published
https://ortelius.io/blog/2024/03/27/what-is-threat-modeling/

**Comment by TracyRagan** [comment]
Completed - edited and published.
