### ISSUE TITLE
First Time Contributor Blog - First Pull Request

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/outreach#6]
Need a blog to explain how to do your first pull request - a demo would be great.

**Comment by moise3** [comment]
Hi @TracyRagan, can you assign this to me?

**Comment by TracyRagan** [comment]
@moise3 It is yours - thanks. And you can find help on this here:
https://ortelius.io/contributor/
https://docs.ortelius.io/guides/contributorguide/
Thanks!

**Comment by TracyRagan** [comment]
closed
