### ISSUE TITLE
First Time Contributor Blog - Getting Help

### ISSUE THREAD

**Issue by TracyRagan** [ortelius/outreach#9]
A blog on how to reach out to the Ortelius contributors and get help when you are stuck on a coding problem.

**Comment by TracyRagan** [comment]
Thank you @afzalbin64

**Comment by TracyRagan** [comment]
Nice job on the blog @afzal442 It is now published with a few minor edits: https://ortelius.io/blog/2023/04/10/getting-started-as-an-ortelius-open-source-contributor/

I will be shared on the Ortleius channels starting this week.

**Comment by afzal442** [comment]
Thank lot @TracyRagan ! Glad to know that. 😄 Exhilarating!
